/**
 * Generates assets/stack.svg: a categorised chip grid of the technical stack.
 *
 * Replaces the shields.io badge rows. Those had a specific problem: dbt,
 * Oracle, Pinecone, AWS, Azure and LinkedIn were all pulled from Simple Icons
 * over trademark, so shields renders them with no glyph while their neighbours
 * keep one. Half the row iconed and half not reads as broken rather than
 * deliberate. Drawing the chips ourselves makes every entry identical, matches
 * vedantmane.vercel.app, and removes twenty external image requests.
 *
 * Layout is computed rather than hand-placed, so adding a technology is one
 * line and the rows re-wrap on their own.
 */
import { writeFileSync } from "node:fs";

/**
 * Only what there is evidence for: the declared stack in the portfolio's
 * site.ts plus what actually appears in the project repositories.
 */
const GROUPS = [
  ["Languages", ["Python", "SQL", "PL/SQL", "TypeScript", "Java", "R"]],
  ["Data platforms", ["Databricks", "Snowflake", "Apache Spark", "PySpark", "Delta Live Tables", "Auto Loader", "Unity Catalog", "Snowpark"]],
  ["Orchestration", ["Apache Airflow", "Azure Data Factory", "dbt", "Snowflake Tasks", "Snowflake Streams", "GitHub Actions"]],
  ["Modelling", ["Dimensional Modelling", "Star Schema", "SCD Type 2", "Normalisation", "Data Quality", "DQX", "Parquet"]],
  ["Databases", ["Oracle", "PostgreSQL", "Azure SQL", "Stored Procedures", "RBAC"]],
  ["ML and RL", ["PyTorch", "TensorFlow", "scikit-learn", "Hugging Face", "LoRA", "PEFT", "PPO", "Deep Q-Networks", "Thompson Sampling", "Gymnasium"]],
  ["Agents and retrieval", ["LangGraph", "LangChain", "CrewAI", "MCP", "RAG", "Pinecone", "ChromaDB", "OpenAI Embeddings"]],
  ["Document AI", ["Mistral OCR", "Docling", "PyMuPDF", "Azure Document Intelligence"]],
  ["Cloud and serving", ["AWS", "Azure", "GCP", "S3", "Key Vault", "Cloud Run", "Docker", "Kubernetes", "FastAPI", "Streamlit", "Vercel"]],
  ["Analytics", ["Tableau", "Power BI", "Alteryx"]],
];

const W = 880;
const PAD = 40;
const LABEL_W = 168;
const CHIP_H = 25;
const CHIP_GAP = 7;
const ROW_GAP = 9;
const GROUP_GAP = 15;
const FONT = 11.5;

// SVG cannot measure text, so widths are estimated. Helvetica's lowercase
// averages ~0.52em; capitals and digits run wider, so they are weighted rather
// than assuming one width for every character. Slightly generous on purpose:
// a chip with too much padding looks intentional, one that clips does not.
const textWidth = (s) => {
  let w = 0;
  for (const ch of s) {
    if (/[A-Z0-9]/.test(ch)) w += FONT * 0.64;
    else if (/[ilIjt.,'\-]/.test(ch)) w += FONT * 0.31;
    else if (/[mwMW]/.test(ch)) w += FONT * 0.86;
    else w += FONT * 0.545;
  }
  return w;
};

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const chipsX = PAD + LABEL_W;
const chipsMax = W - PAD;

let y = 84;
let body = "";
let delay = 0.15;

for (const [label, items] of GROUPS) {
  const startY = y;
  let x = chipsX;
  let lines = 1;
  let chips = "";

  for (const item of items) {
    const w = Math.round(textWidth(item) + 22);
    if (x + w > chipsMax) {
      x = chipsX;
      y += CHIP_H + ROW_GAP;
      lines++;
    }
    chips +=
      `      <g opacity="1"><animate attributeName="opacity" values="0;1" dur="0.45s" begin="${delay.toFixed(2)}s" fill="freeze"/>` +
      `<rect x="${x}" y="${y}" width="${w}" height="${CHIP_H}" rx="6" fill="#101116" stroke="#22242e"/>` +
      `<text x="${x + w / 2}" y="${y + 16.5}" text-anchor="middle" font-size="${FONT}" fill="#c9cad2">${esc(item)}</text></g>\n`;
    x += w + CHIP_GAP;
    delay += 0.012;
  }

  // The label sits centred against however many lines its chips wrapped to.
  const labelY = startY + ((lines - 1) * (CHIP_H + ROW_GAP)) / 2 + 17;
  body +=
    `    <text x="${PAD}" y="${labelY}" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" ` +
    `font-size="10" letter-spacing="1.2" fill="#5a5a64">${esc(label.toUpperCase())}</text>\n${chips}`;

  y += CHIP_H + GROUP_GAP;
  delay += 0.03;
}

const H = y + PAD - GROUP_GAP;
const count = GROUPS.reduce((n, [, items]) => n + items.length, 0);

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Technical stack: ${GROUPS.map(
  ([l, i]) => `${l}: ${i.join(", ")}`,
).join(". ")}">
  <title>Technical stack</title>
  <!-- GENERATED by scripts/build-stack.mjs. Edit that, not this file. -->
  <clipPath id="cardT"><rect width="${W}" height="${H}" rx="14"/></clipPath>

  <g clip-path="url(#cardT)" font-family="Helvetica Neue, Helvetica, Arial, sans-serif">
    <rect width="${W}" height="${H}" fill="#08090b"/>

    <text x="${PAD}" y="44" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="11.5" letter-spacing="2" fill="#5a5a64">TECHNICAL STACK</text>
    <text x="${W - PAD}" y="44" text-anchor="end" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="10" letter-spacing="1.2" fill="#3f4048">${count} &#183; USED IN SHIPPED WORK</text>
    <line x1="${PAD}" y1="60" x2="${W - PAD}" y2="60" stroke="#1a1b22" stroke-width="1"/>

${body}
    <rect width="${W}" height="${H}" rx="14" fill="none" stroke="#212229" stroke-width="1"/>
  </g>
</svg>
`;

writeFileSync(new URL("../assets/stack.svg", import.meta.url), svg);
console.log(`stack.svg written: ${count} technologies across ${GROUPS.length} groups, ${H}px tall`);
