/**
 * Generates assets/contact.svg: a profile card with the LinkedIn identity
 * rendered inline.
 *
 * LinkedIn's own embed badge needs JavaScript, and GitHub strips scripts and
 * iframes from README HTML, so a live widget is not possible on a profile page.
 * This draws the same information instead: avatar, name, headline and handle,
 * with the LinkedIn mark, so the profile appears inline rather than as a badge
 * that only says the word "LinkedIn".
 *
 * The avatar is embedded as a data URI. An SVG loaded through GitHub's image
 * proxy cannot fetch a second remote asset, so anything referenced by URL would
 * render as a blank box. It is downscaled first to keep the file small.
 *
 * Note the card is an image, so links inside it are not clickable. The README
 * puts real markdown links directly beneath it.
 */
import { writeFileSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

const AVATAR_SRC = "/Users/vedant/Desktop/Projects/portfolio-website/public/memoji.png";
const OUT = new URL("../assets/contact.svg", import.meta.url);

const LINKEDIN_PATH =
  "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.125 2.062 2.062 0 0 1 0 4.125zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z";
const MAIL_PATH =
  "M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm0 4-8 5-8-5V6l8 5 8-5v2z";
const PIN_PATH =
  "M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5z";
const GLOBE_PATH =
  "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm6.93 6h-2.95a15.65 15.65 0 0 0-1.38-3.56A8.03 8.03 0 0 1 18.93 8zM12 4.04c.83 1.2 1.48 2.53 1.91 3.96h-3.82c.43-1.43 1.08-2.76 1.91-3.96zM4.26 14a7.82 7.82 0 0 1 0-4h3.38a16.5 16.5 0 0 0 0 4H4.26zm.81 2h2.95c.32 1.25.78 2.45 1.38 3.56A7.99 7.99 0 0 1 5.07 16zm2.95-8H5.07a7.99 7.99 0 0 1 4.33-3.56A15.65 15.65 0 0 0 8.02 8zM12 19.96c-.83-1.2-1.48-2.53-1.91-3.96h3.82c-.43 1.43-1.08 2.76-1.91 3.96zM14.34 14H9.66a14.7 14.7 0 0 1 0-4h4.68a14.7 14.7 0 0 1 0 4zm.25 5.56c.6-1.11 1.06-2.31 1.38-3.56h2.95a7.99 7.99 0 0 1-4.33 3.56zM16.36 14a16.5 16.5 0 0 0 0-4h3.38a7.82 7.82 0 0 1 0 4h-3.38z";

/** Downscale with sips (macOS built-in) so no image library is needed here. */
function avatarDataUri() {
  try {
    const tmp = "/tmp/_avatar-96.png";
    execFileSync("sips", ["-Z", "96", AVATAR_SRC, "--out", tmp], { stdio: "ignore" });
    return `data:image/png;base64,${readFileSync(tmp).toString("base64")}`;
  } catch {
    return null; // Card still renders, just without the portrait.
  }
}

const W = 880;
const H = 208;
const avatar = avatarDataUri();

const row = (y, path, color, label, value) => `
      <g transform="translate(214,${y})">
        <path d="${path}" fill="${color}" transform="scale(0.72)"/>
        <text x="30" y="13.5" font-size="13" fill="#9a9aa4">${label}</text>
        <text x="${30 + label.length * 6.6 + 10}" y="13.5" font-size="13" fill="#f1f1f2">${value}</text>
      </g>`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Contact Vedant Mane. LinkedIn in/vedant-mane. Email vedant12mane@gmail.com. Portfolio vedantmane.vercel.app. Based in Boston, Massachusetts.">
  <title>Contact Vedant Mane</title>
  <!-- GENERATED by scripts/build-contact.mjs. Edit that, not this file. -->

  <defs>
    <clipPath id="cardC"><rect width="${W}" height="${H}" rx="14"/></clipPath>
    <clipPath id="avaC"><circle cx="122" cy="104" r="52"/></clipPath>
    <linearGradient id="liGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0A66C2"/><stop offset="100%" stop-color="#0a4f96"/>
    </linearGradient>
  </defs>

  <g clip-path="url(#cardC)" font-family="Helvetica Neue, Helvetica, Arial, sans-serif">
    <rect width="${W}" height="${H}" fill="#08090b"/>
    <rect x="0" y="0" width="4" height="${H}" fill="url(#liGrad)"/>

    ${
      avatar
        ? `<circle cx="122" cy="104" r="53" fill="#101116" stroke="#22242e"/>
    <image href="${avatar}" x="70" y="52" width="104" height="104" clip-path="url(#avaC)" preserveAspectRatio="xMidYMid slice"/>`
        : `<circle cx="122" cy="104" r="53" fill="#101116" stroke="#22242e"/>`
    }

    <!-- Available dot, same breathing rhythm as the header card. -->
    <circle cx="160" cy="142" r="8" fill="#08090b"/>
    <circle cx="160" cy="142" r="5.5" fill="#4ade80">
      <animate attributeName="opacity" values="1;0.4;1" dur="2.6s" repeatCount="indefinite"/>
    </circle>

    <text x="214" y="56" font-size="24" font-weight="700" letter-spacing="-0.6" fill="#f1f1f2">Vedant Mane</text>
    <text x="214" y="78" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="11.5" letter-spacing="1.6" fill="#8ba4ff">DATA ENGINEER &amp; AI DEVELOPER</text>
${row(96, LINKEDIN_PATH, "#0A66C2", "LinkedIn", "in/vedant-mane")}
${row(126, MAIL_PATH, "#8ba4ff", "Email", "vedant12mane@gmail.com")}
${row(156, GLOBE_PATH, "#8ba4ff", "Portfolio", "vedantmane.vercel.app")}

    <g transform="translate(700,96)">
      <path d="${PIN_PATH}" fill="#5a5a64" transform="scale(0.7)"/>
      <text x="24" y="12" font-size="12.5" fill="#6e6e78">Boston, MA</text>
    </g>
    <text x="700" y="140" font-size="12.5" fill="#4ade80">Available to work</text>
    <text x="700" y="164" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="10" letter-spacing="1.1" fill="#3f4048">OPEN TO DATA &amp; AI ROLES</text>

    <rect width="${W}" height="${H}" rx="14" fill="none" stroke="#212229" stroke-width="1"/>
  </g>
</svg>
`;

writeFileSync(OUT, svg);
console.log(
  `contact.svg written${avatar ? " with embedded avatar" : " (avatar unavailable, card still valid)"}, ${(svg.length / 1024).toFixed(1)}KB`,
);
