/**
 * Regenerates assets/stats.svg from the live GitHub API.
 *
 * Run by .github/workflows/stats.yml on a schedule. The point of generating our
 * own card rather than embedding a third-party stats service is that the design
 * stays ours, there is no external rate limit to hit, and nothing on the profile
 * breaks when someone else's server does.
 *
 * Works with or without a token. GITHUB_TOKEN in Actions unlocks the GraphQL
 * contribution count; without one the script still produces a complete card and
 * substitutes the account age, so a local preview matches what CI will publish
 * in every respect except that one figure.
 */
import { writeFileSync } from "node:fs";

const ACCOUNTS = ["vedantmane12", "vedantmane"];
const PRIMARY = "vedantmane12";
const YEARS_IN_PRODUCTION = "3+"; // Tata Consultancy Services. Not derivable from the API.

const token = process.env.GITHUB_TOKEN;
const headers = {
  Accept: "application/vnd.github+json",
  "User-Agent": "vedantmane12-profile",
  ...(token ? { Authorization: `Bearer ${token}` } : {}),
};

async function repos(user) {
  const out = [];
  for (let page = 1; page <= 4; page++) {
    const res = await fetch(
      `https://api.github.com/users/${user}/repos?per_page=100&page=${page}`,
      { headers },
    );
    if (!res.ok) throw new Error(`${user} repos: ${res.status} ${await res.text()}`);
    const batch = await res.json();
    out.push(...batch);
    if (batch.length < 100) break;
  }
  return out;
}

/** Contribution count needs GraphQL, which needs a token. Optional by design. */
async function contributions(user) {
  if (!token) return null;
  const res = await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `query($login:String!){user(login:$login){contributionsCollection{contributionCalendar{totalContributions}}}}`,
      variables: { login: user },
    }),
  });
  if (!res.ok) return null;
  const json = await res.json();
  return json?.data?.user?.contributionsCollection?.contributionCalendar
    ?.totalContributions ?? null;
}

const relative = (iso) => {
  const days = Math.floor((Date.now() - new Date(iso)) / 86400000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 30) return `${days} days ago`;
  const months = Math.floor(days / 30);
  return months < 12 ? `${months} mo ago` : `${Math.floor(days / 365)} yr ago`;
};

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * One figure. Every animated element also carries its final static value:
 * GitHub serves this through an image proxy, and a renderer that ignores SMIL
 * has to show a finished card rather than an empty one.
 */
function stat({ x, value, suffix, label, delay }) {
  return `      <g transform="translate(${x},0)" opacity="1">
        <animate attributeName="opacity" values="0;1" dur="0.5s" begin="${delay}s" fill="freeze"/>
        <text y="120" font-size="42" font-weight="700" letter-spacing="-1.2" fill="#f1f1f2">${esc(value)}${
          suffix ? `<tspan font-size="26" fill="#8ba4ff">${esc(suffix)}</tspan>` : ""
        }</text>
        <text y="146" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
              font-size="11" letter-spacing="1.3" fill="#6e6e78">${esc(label)}</text>
      </g>`;
}

const all = (await Promise.all(ACCOUNTS.map(repos))).flat();
const own = all.filter((r) => !r.fork);
const since = new Date(all.map((r) => r.created_at).sort()[0]).getUTCFullYear();
const lastPush = all.map((r) => r.pushed_at).sort().at(-1);
const contribs = await contributions(PRIMARY);

const figures = [
  { value: own.length, label: "REPOSITORIES", delay: 0.25 },
  contribs !== null
    ? { value: contribs.toLocaleString("en-US"), label: "CONTRIBUTIONS, 12 MO", delay: 0.4 }
    : { value: since, label: "ON GITHUB SINCE", delay: 0.4 },
  { value: YEARS_IN_PRODUCTION.replace("+", ""), suffix: "+", label: "YEARS IN PRODUCTION", delay: 0.55 },
  { value: relative(lastPush), label: "LAST SHIPPED", delay: 0.7 },
];

// Columns are placed by measured-ish width rather than evenly, because
// "3 days ago" and "54" are very different sizes and an even split leaves the
// short ones marooned.
const xs = [48, 252, 476, 676];

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 880 210" width="880" height="210" role="img" aria-label="${figures
  .map((f) => `${f.value}${f.suffix ?? ""} ${f.label.toLowerCase()}`)
  .join(", ")}">
  <title>Profile at a glance</title>
  <!-- GENERATED by scripts/build-stats.mjs. Edit that, not this file. -->

  <defs>
    <linearGradient id="rule" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#3355ff"/><stop offset="100%" stop-color="#8ba4ff" stop-opacity="0.15"/>
    </linearGradient>
    <clipPath id="cardS"><rect width="880" height="210" rx="14"/></clipPath>
  </defs>

  <g clip-path="url(#cardS)">
    <rect width="880" height="210" fill="#08090b"/>

    <text x="48" y="44" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="11.5" letter-spacing="2" fill="#5a5a64">AT A GLANCE</text>
    <text x="832" y="44" text-anchor="end" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="10" letter-spacing="1.2" fill="#3f4048">LIVE &#183; REBUILT DAILY</text>

    <line x1="48" y1="60" x2="48" y2="60" stroke="url(#rule)" stroke-width="1.5">
      <animate attributeName="x2" from="48" to="832" dur="1.2s" fill="freeze"
               calcMode="spline" keySplines="0.16 1 0.3 1"/>
    </line>

    <g font-family="Helvetica Neue, Helvetica, Arial, sans-serif">
${figures.map((f, i) => stat({ ...f, x: xs[i] })).join("\n")}
    </g>

    <text x="48" y="182" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
          font-size="9.5" letter-spacing="1.1" fill="#3f4048">UPDATED ${esc(
            new Date().toISOString().slice(0, 10),
          )} &#183; GENERATED FROM THE GITHUB API</text>

    <rect width="880" height="210" rx="14" fill="none" stroke="#212229" stroke-width="1"/>
  </g>
</svg>
`;

writeFileSync(new URL("../assets/stats.svg", import.meta.url), svg);
console.log(
  `stats.svg written: ${own.length} repos, since ${since}, last push ${relative(lastPush)}` +
    (contribs !== null ? `, ${contribs} contributions` : ", contributions skipped (no token)"),
);
